### ISSUE TITLE
[Stage 2: cli] Verify environments stage 2 part 1 work

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/cli#223]
**Description**

Verify environments stage 2 part 1 work through the cli 

**List of tasks**
- [x]  Resources
    - [x]  Response for resource endpoints should include info on the environment its in
    - [x]  Resources can be created in a specific environment
    - [x]  Resource status worker should update it's status
    - [x]  Resource with an SSH tunnel can be created
    - [x]  Resource with an SSH tunnel can have it's keys rotated
    - [x]  Resource with an SSH tunnel can be validated 
    - [x]  Resource can be deleted
    - [x]  Resource can be updated 
- [x]  Pipelines
    - [x]  Response for pipeline endpoints should include info on the environment its in
    - [x]  Pipelines can be created in a specific environment
- [x]  Connectors
    - [x]  Response for connector endpoints should include info on the environment its in
    - [x]  Connectors can be created in a specific environment
    - [x]  Connectors validate that pipeline and resources are in the same env
    - [x]  Connector status worker should update it's status
    - [x]  Connector can be paused, restarted, resumed 
    - [x]  Connector can be deleted
    - [x]  Connector can be updated 
- [x] End to end
    - [x] 2 resources, a pipeline, and 2 connectors created in an environment
    - [x] check that the data is syncing to the destination resource  

**Additional context**

The checklist can be found here: https://www.notion.so/meroxa/Environment-Implementation-Plan-Stage-2-60970cbce0a44c2b9095c0fea4172a69#11970f4b927347b0abbe0fa775b79489

**Comment by janelletavares** [comment]
https://gist.github.com/janelletavares/79795a2af8099f339353ad5cd3cdac24 notes on CLI commands
