### ISSUE TITLE
Pass SSH tunnel keys as files in CLI

### ISSUE THREAD

**Issue by lyuboxa** [meroxa/cli#273]
Resources with SSH tunnels can be created with an optional private ssh key.

Currently the key is provided as a string via `--ssh-private-key` via the CLI. 
This process can be somewhat cumbersome and lead to failures if the key string is not properly
escaped. 

To improve the UX, another option can be added `--ssh-private-key-file` where the contents of the
key can be read from a file without the need to splat it on the command line.

**Comment by janelletavares** [comment]
https://github.com/meroxa/cli/issues/381 fixed here
