### ISSUE TITLE
[CLI] Error on github login through CLI 

### ISSUE THREAD

**Issue by anna-cross** [meroxa/cli#339]
**Describe the bug**  

Cannot login to meroxa through Github when doing a 'meroxa login' through CLI. This problem only exists on CLI, but not when I go directly to dashboard.meroxa.io and login through Github. 

**Machine (please complete the following information):**  

 - OS: WINDOWS - (using Windows Subsystem for Linux)
 - CLI Version : v2.0.0-alpha.3  (latest CLI pull)

**To Reproduce**  

1. Log out of your current account if you are signed in on either dashboard.meroxa.io or dashbord.dev.meroxa.io 
2. Either in dev or prod env: run `meroxa login` from your command line 
3. It should take you to this page: 
4. 
![image](https://user-images.githubusercontent.com/96070127/165963907-7d3491cf-f159-4ee9-b808-289a5879e038.png)
5. Click Github as login 
6. You should immediately see : 
![image](https://user-images.githubusercontent.com/96070127/165964052-dcb84ba9-3aed-4cbf-bdf4-917077f74188.png)
7. This is the output by CLI 
![image](https://user-images.githubusercontent.com/96070127/165964117-c3fc8da1-4c22-4300-b478-f357b92702e1.png)

**Expected behavior**  
What did you expect to happen? 

No

**Comment by justmisosoup** [comment]
Identified this risk during AWS Marketplace Integration discussions. This could cause issues if the customer opts to sign up using GitHub versus Google SSO or Username / Password.

**Comment by jayjayjpg** [comment]
I can confirm that this is a reproducible bug and may be related to a missing / mismatched auth0 configuration. To confirm what causes the issue, this would need more investigation.

![githubsignup2](https://user-images.githubusercontent.com/8811742/226920170-6878a3c4-0c2c-4861-93da-2defb3b24f28.gif)

**Comment by jayjayjpg** [comment]
@jmar910 fixed this issue [last week](https://github.com/meroxa/auth0-templates/pull/176) and this is now working again as follows:

![auth-prod-cli](https://user-images.githubusercontent.com/8811742/227909443-3e2244cc-9146-4e07-aed4-dbee567466ac.gif)

**Comment by janelletavares** [comment]
I was able to authenticate with the CLI today (now that github auth is back up).  @anna-cross are you still having this problem?  Is it potentially specific to Windows?
![Screenshot from 2023-03-27 15-46-40](https://user-images.githubusercontent.com/12731615/227958100-e95de35f-d33f-4d3a-9549-b2289e6e0b58.png)
![Screenshot from 2023-03-27 15-47-01](https://user-images.githubusercontent.com/12731615/227958144-52aced71-5264-48ce-b2dc-af50843f9276.png)
