### ISSUE TITLE
Handle gracefully an older version of a turbine library in the CLI

### ISSUE THREAD

**Issue by raulb** [meroxa/cli#378]
CLI always relies on customers using the latest versions of different turbine libraries. However, users aren't likely to update their turbine applications as much as we do. In some situations, the CLI might be relying on some functionality not yet available on customer turbine applications. In those cases, the CLI should handle gracefully these scenarios and:

1. Indicate the disparity of versions in a way that doesn't look like an error.
2. Indicate how to proceed with a turbine library upgrade (maybe with a link to our documentation on how to do that).

This issue would fix a scenario like the one that was presented yesterday to DeVaris in which our CLI was checking for the availability on resources making use of a flag recently introduced in turbine-go, but that was not available in DeVaris' turbine-go app version:

```
➜  poskappa git:(main) meroxa apps deploy
Checking for uncommitted changes...
	✔ No uncommitted changes!
Validating branch...
	✔ Deployment allowed from main branch!
Preparing application "poskappa" (golang) for deployment...
	✔ Application built!
	⠋Checking resource availability for application "poskappa" (golang) befo
	⠙Checking resource availability for application "poskappa" (golang) befo
	⠹Checking resource availability for application "poskappa" (golang) befo
	⠸Checking resource availability for application "poskappa" (golang) befo
	⠼Checking resource availability for application "poskappa" (golang) befo
	⠴Checking resource availability for application "poskappa" (golang) before deployment...Error: unable to read resource definition from app: flag provided but not defined: -listresources
Usage of /Users/devaris/Code/turb-demo/poskappa/poskappa:
  -deploy
    	deploy the data app
  -imagename string
    	image name of function image
  -listfunctions
    	list available functions
  -serve string
    	serve function via gRPC
```

**Comment by simonl2002** [comment]
+1 on this. Ran into this after taking over an app that was created with an older turbine version. The errors returned were very unhelpful. I then had to compare my app.go vs a newly generated one.

**Comment by janelletavares** [comment]
proposed implementation:
keeping track of required (>=) turbine lib versions in CLI
turbine libs have a command to return their version

**Comment by janelletavares** [comment]
related https://github.com/meroxa/platform-api/issues/1130

**Comment by janelletavares** [comment]
depends on https://github.com/meroxa/turbine-project/issues/266

**Comment by janelletavares** [comment]
flag mismatches handled by https://github.com/meroxa/product/issues/598
