### ISSUE TITLE
Make creating a resource with an SSH key more clear

### ISSUE THREAD

**Issue by janelletavares** [meroxa/cli#381]
**Describe the bug**  

s/--ssh-private-key/--ssh-private-key-file
update docs as necessary

make sure we are displaying all the error information details from the API

**Machine (please complete the following information):**  

 - CLI Version [e.g. 22]

**To Reproduce**  

What can we do to reproduce your bug?

Please provide:
- Relevent CLI commands
- Relevent environment details

**Expected behavior**  
What did you expect to happen? 

**Screenshots**  
If applicable, add screenshots to help explain your problem. (Be sure to scrub any sensitive information.)

**Additional context**

**Comment by justmisosoup** [comment]
We discussed in stand up there's two problems to be solved regarding SSH tunnel experience in the Meroxa CLI. 

1. First problem: When there is a formatting issue with a Private SSH Key, the Meroxa CLI prints an unhelpful `internal error`. We should provide an actionable error. An example: When an Private SSH Key has extra whitespace where it is not expected. At a minimum, we should tell the customer the format is incorrect and ask them to check the format of their Private SSH Key.

Related issue: https://github.com/meroxa/platform-api/issues/1206

2. Second problem: When a Private SSH key is passed to the Meroxa Platform, this is done by using `--ssh-private-key <PRIVATE_SSH_KEY_HERE>`. The customer must copy and paste the Private SSH Key into their command. This could lead to a number of experience issues.
    - Increasing the chase of formatting issues.
    - Potential issue with caching the Private Key on the terminal. 

Related issue: https://github.com/meroxa/cli/issues/381
