### ISSUE TITLE
[Ruby: cli] Refactor calls to --listresources and --listfunctions

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/cli#520]
## Metadata 

- [Implementation plan](https://www.notion.so/meroxa/Turbine-Ruby-Implementation-Plan-ba3f655e7eea4697bf27d3fbf2fa45d3)

## Context 

~~CLI can be simplified by removing Turbine calls to --listresources and --listfunctions, and instead getting the necessary information from the deployment spec.~~

As we are reverting default IR changes, we are keeping calls to listresources and listfunctions, but also adding checks on IR specs. 

If https://github.com/meroxa/turbine-core/issues/9 has not been completed, ensure that the [IR DeploymentSpec struct](https://github.com/meroxa/turbine-core/blob/8c2173967752a10c9311d4da6729817da88f48b2/pkg/ir/spec.go#L16) has a function to populate function image. This function will be used by the CLI to populate the image after it is done building. 

## Acceptance 

- [ ] Refactor CLI to use IR spec along side with making calls  to --listresources and --listfunctions.

**Comment by anna-cross** [comment]
At the current moment, we have reverted default use of IR back to old orchestration. For Ruby, we will be using the listresource and listfunction calls to mirror other languages for now. Closing this.
