### ISSUE TITLE
[Turbine Data Flow] Add link to the Applications Details dashboard page on `meroxa apps describe`

### ISSUE THREAD

**Issue by nassor** [meroxa/cli#535]
Expected Change: https://www.notion.so/meroxa/Turbine-Data-Flow-Implementation-Plans-6d4780375ddc4ca99a5ce7a97200bb1e#26b32621944a4384bf8df502a78ba874

**Comment by janelletavares** [comment]
https://github.com/meroxa/cli/pull/538
