### ISSUE TITLE
[Turbine Data Flow] Propagate CLI details over HTTP headers

### ISSUE THREAD

**Issue by nassor** [meroxa/cli#536]
Expected Change: https://www.notion.so/meroxa/Turbine-Data-Flow-Implementation-Plans-6d4780375ddc4ca99a5ce7a97200bb1e#6c0aa9405e0940c5a15640bd929adf25

If the header `Meroxa-CLI-App-Version` demands changes in the turbine-specific languages, we will probably move that into Phase 2 or a KTLO task.

**Comment by janelletavares** [comment]
https://github.com/meroxa/cli/pull/547

**Comment by justmisosoup** [comment]
Needs: https://github.com/meroxa/product/issues/614
