### ISSUE TITLE
Update `resources list` output to display URL to dashboard list view

### ISSUE THREAD

**Issue by justmisosoup** [meroxa/cli#541]
## Description

With Phase 1 of the Turbine Data Flow project we will be introducing a paradigm which displays the dashboard URL `https://dashboard.meroxa.io/apps` as part of the command output of `meroxa apps list`. 

We need to also reflect this paradigm for other relevant views. In this case, we will also display the dashboard URL `https://dashboard.meroxa.io/resources` as part of the command output of `meroxa resources list`.

```
$ meroxa resources ls
                 UUID                     NAME         TYPE       ENVIRONMENT                                             URL                                              TUNNEL   STATE
====================================== =========== ============= ============= ========================================================================================== ======== =======
 28dde4d5-9cd9-4b29-8ba1-52747ac12345   pg          postgres      common        postgres://diffuser-4.dsag1eaw3rw.us-east-1.rds.amazonaws.com:5432/diffuser                N/A     ready

✨ To visualize your resources, visit https://dashboard.meroxa.io/resources
```

**Comment by janelletavares** [comment]
https://github.com/meroxa/cli/pull/549
