### ISSUE TITLE
[Env: cli] Environment support for `apps deploy`

### ISSUE THREAD

**Issue by anna-cross** [meroxa/cli#595]
## Metadata 
- [Implementation plan](https://www.notion.so/meroxa/Environments-Turbine-Support-Implementation-Plan-8aa02e78eaec453ab6b47ff9d5c2a9ed)

**Depends on**

- [x] https://github.com/meroxa/turbine-core/issues/80

## Context 

In order to allow for application deployment in an environment, we need to modify 'apps deploy' command in our CLI to accept a new flag '--env'. When no value is passed to an environments flag, we need to assume a common env. 

## Acceptance 
- [x] Add a new flag '--env' to `meroxa apps deploy` command, to change [flags](https://github.com/meroxa/cli/blob/2beca0629ecac6cd32e101da26b67b50676c2df9/cmd/meroxa/root/apps/deploy.go#:~:text=Deploy%20struct%20%7B-,flags,-struct%20%7B) 
- [x] The flag's information should be passed with Application info to API 
~- [ ] When there is no '—env' value, assume 'common'~

**Comment by raulb** [comment]
For the record, on:

` When there is no '—env' value, assume 'common'` I'll leave the API to figure that out. In other words, when no environment information is sent out, Platform API should assume is common environment.
