### ISSUE TITLE
[Env: cli] Descriptive error when creating an app in a non existing env

### ISSUE THREAD

**Issue by dianadoherty** [meroxa/cli#621]
## Context 

When creating an app in an environment that doesn't exist, we don't get a good error message.

```
meroxa apps deploy --env bad-aws
Validating your app.json...
	✔ Checked your language is "ruby"
	✔ Checked your application name is "test-rb"
Checking for uncommitted changes...
	✔ No uncommitted changes!
Error: could not find environment
```

## Acceptance

- [ ] Ensure API has a clearer message for when an app fails to deploy in an environment

**Comment by lyuboxa** [comment]
The check for the existence of an environment can be pushed earlier in the stack for validation. This will allow us to exit sooner and recommend action to the user.
