### ISSUE TITLE
Nightly builds are not using the latest semantic versioned tag

### ISSUE THREAD

**Issue by janelletavares** [meroxa/cli#657]
**Describe the bug**  

The git describe command takes a glob pattern when looking for a specific tag.  However, glob patterns seen to not have any wiggle room for the number of digits in the match.  Therefore, even though the minor tags have advanced past 9, it has only been picking up 9.

**Expected behavior**  
It should find the latest tag, no matter how many digits are in the major, minor, or bug version.

**Screenshots**  
![Screenshot from 2023-03-20 13-15-40](https://user-images.githubusercontent.com/12731615/226336714-f851372c-2945-4380-8d9c-4f19af9d86e3.png)

**Comment by Mehdi207-mp** [comment]
Thanks
