### ISSUE TITLE
Make upgrading a python app more predictable

### ISSUE THREAD

**Issue by janelletavares** [meroxa/cli#678]

**Comment by nassor** [comment]
Check with Team Water the prospect of migrating to turbine-core.

**Comment by ericcheatham** [comment]
Confirmed with Team Water that the Turbine-core/Turbine-IR work kickoff is this upcoming week. Meroxa-py will become irrelevant in that work and therefore this task is unnecessary.

**Comment by janelletavares** [comment]
> Confirmed with Team Water that the Turbine-core/Turbine-IR work kickoff is this upcoming week. Meroxa-py will become irrelevant in that work and therefore this task is unnecessary.

@ericcheatham does that confirm that there is no upgrade path for older apps, just need to delete and recreate?
