### ISSUE TITLE
[IR/Core Migration] Update go app `init` command to use turbine-core

### ISSUE THREAD

**Issue by jmar910** [meroxa/cli#686]
As part of Go app initialization, update the Init function to call turbine-core's NewApp Init function.
[EXAMPLE](https://github.com/meroxa/cli/blob/master/cmd/meroxa/turbine/ruby/init.go#L10-L12)

## Dependencies
+ [x] https://github.com/meroxa/turbine-go/issues/133

**Comment by raulb** [comment]
This is currently blocked on somethings we need to modify. Tackling that now https://github.com/meroxa/turbine-core/issues/109
