### ISSUE TITLE
[IR/Core Migration] Update turbine-go deploy implementation to use turbine-core

### ISSUE THREAD

**Issue by jmar910** [meroxa/cli#687]
The `CreateDockerfile` implementation should be updated to:
+ [x] Call turbine-go to create the Dockerfile

The `SetupForDeploy` implementation should be updated to:
+ [x] Boot the `record` server
+ [x] Call turbine-go with the user's data app (See https://github.com/meroxa/turbine-go/issues/136)

The implementations that check the app (`GetResources`) should be updated to use app information from the `record` server

[EXAMPLE](https://github.com/meroxa/cli/blob/master/cmd/meroxa/turbine/ruby/deploy.go)

## Dependencies
+ [x] https://github.com/meroxa/turbine-go/issues/136

**Comment by raulb** [comment]
Currently blocked on https://github.com/meroxa/turbine-go/issues/148.
