### ISSUE TITLE
[IR/Core Migration] Update turbine-go run implementation to use turbine-core

### ISSUE THREAD

**Issue by jmar910** [meroxa/cli#688]
The CLI interactions with turbine-core should produce the following workflow during `Run`: 

1. Boot turbine-core's `run` server
2. Execute the user's data app using the run grpc client
3. Decide whether a user has a function or not based on information returned from previous steps, if not, go to Step 9
4. Boots the user's function as a grpc service
5. Load fixture data
6. Execute fixtures against the function service
7. Output the response from the function service
8. Shut down function service
9. If there is no function, output the fixtures and what destinations they are going to

**Comment by raulb** [comment]
This was done by https://github.com/meroxa/cli/pull/711. Closing cc @jmar910
